theme: jekyll-theme-minimal
baseurl: /snippets/ 
url: http://rosikand.github.io
collections:
  computer_science:
    output: true
  mathematics:
    output: true
  python:
    output: true
  miscellany:
    output: true
  machine_learning:
    output: true
  data_structures_and_algorithms:
    output: false
